sudo: required
services:
  - docker

before_install:
  - docker build -t rkshjoshi\udemy-docker -f Dockerfile.dev  .

script:
  - docker run -e CI=true rkshjoshi\udemy-docker npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: udemy-docker
    env: UdemyDocker-env
    bucket_name: "elasticbeanstalk-us-east-1-541393959806"
    bucket_path: udemy-docker
    on:
      branch: master
    access_key_id: $AWS_Access_Key
    secret_access_key: $AWS_Secret_Key
